### PR TITLE
Add support for ghc-9.6

### LINKED ISSUE #6: Bounds for GHC 9.1
Hi @hvr!

I'm a user of this excellent package and I've noticed the bounds are too restrictive for GHC 9.1 that is already released. Also, the bounds for QuickCheck are stricter than they'd need to be. Would you like to fix those on Hackage? Or can I help, e.g., by preparing a PR and possibly making a release? I may even take over the package temporarily, if you wish so, until you feel like maintaining it again.

All the best,
Mikolaj

### PR DESCRIPTION
**Pull request by erikd**
Addendum (Andreas):  Fixes #6.
- #6

### CODE REVIEW

**Comment by erikd** [comment]
Ping?

**Comment by ncaq** [comment]
I get unneed warn message by Stack.

```
Warning: Ignoring int-cast's bounds on base (>=4.7 && <4.16) and using base-4.16.4.0.
         Reason: allow-newer enabled.
```

I think solve it to merge.

**Comment by erikd** [comment]
@ncaq What is the reproduction for this?I am just using `cabal` and I see no error.

In fact, this PR should address that warning you are seeing.

**Comment by ncaq** [comment]
I am not fluent in English, so my writing style is bad.
Sorry.

I think that merging this PR will also solve the problem I presented.
So I encouraged them to merge it by all means.

**Comment by andreasabel** [comment]
@erikd wrote:
> Ping?

Thanks for the PR!   You can ping me as I am currently acting steward for @hvr 's packages on this organisation.

**Pull request merged**
